### ISSUE TITLE
Testy jednostkowe

### ISSUE THREAD

**Issue by 090393** [090393/Text-Transformer#35]
- [x] Stworzenie co najmniej 2 klas testujących i 20 metod testujących
- [x] Metoda testująca posiada min. 1 asercję i testuje jeden typ zachowania
- [ ] Przetestowanie przynajmniej 10 wywołań metod z zewnętrznych klas testujących za pomocą mock objectów

**Comment by 64-RD** [comment]
Testy na zielono
